server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: C:\Users\Shashank Tiwari\OneDrive\Desktop\Code\PyhtonApp\loki-windows-amd64.exe\positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push


scrape_configs:
  - job_name: myapp
    static_configs:
      - targets:
          - localhost
        labels:
          job: myapp
          filename: "C:\\logs\\app.log"
          __path__: "C:\\Users\\Shashank Tiwari\\OneDrive\\Desktop\\Code\\PyhtonApp\\loki-windows-amd64.exe\\app.log"